// Catálogo precargado de marcas (≥600). La app suma además las marcas que se usen en los perfumes.
export const BRAND_SEED = [
  '27 87 Perfumes',
  '4160 Tuesdays',
  '4711',
  'Abdul Samad Al Qurashi',
  'Abercrombie & Fitch',
  'Acca Kappa',
  "Acqua dell'Elba",
  'Acqua di Parma',
  'Acqua di Selva',
  'Adidas',
  'Adolfo Domínguez',
  'Aedes de Venustas',
  'Aerin',
  'Aeropostale',
  'Aesop',
  'Afnan',
  'Aftelier',
  'Agatha Ruiz de la Prada',
  'Agent Provocateur',
  'Agnès b.',
  'Agonist',
  'Ahmed Al Maghribi',
  'Aigner',
  'AJ Arabia',
  'Ajmal',
  'Al Haramain',
  'Al Rehab',
  'Al Wataniah',
  'Alaïa',
  'Alberta Ferretti',
  "Alessandro Dell'Acqua",
  'Alexander McQueen',
  'Alexandre.J',
  'Alexandria Fragrances',
  'Alfred Sung',
  'American Eagle',
  'Amouage',
  'Amouroud',
  'Anatole Lebreton',
  'Anfas Al Khaleej',
  'Ángel Schlesser',
  'Anna Sui',
  'Anne Klein',
  'Annick Goutal',
  'Antica Farmacista',
  'Antonio Banderas',
  'Antonio Puig',
  'April Aromatics',
  'Aquascutum',
  'Aquolina',
  'Arabian Oud',
  'Aramis',
  'Arcana',
  'Ard Al Khaleej',
  'Ard Al Zaafaran',
  'Areej Le Doré',
  'Ariana Grande',
  'Armaf',
  'Armand Basi',
  'Armani Privé',
  'Aroma Workshop',
  'Arquiste',
  'Arrogance',
  'Asdaaf',
  'Aston Martin',
  'Atelier Cologne',
  'Ateliers Bitter',
  'Atkinsons',
  'Atyab Al Marshoud',
  'Avon',
  'Axe',
  'Ayat Perfumes',
  'Azzaro',
  'Bait Al Bakhoor',
  'Baldessarini',
  'Balenciaga',
  'Bally',
  'Balmain',
  'Banana Republic',
  'Bath & Body Works',
  'BDK Parfums',
  'Benetton',
  'Bentley',
  'Betsey Johnson',
  'Betty Barclay',
  'Beyoncé',
  'Bharara',
  'Biehl Parfumkunstwerke',
  'Bill Blass',
  'Bimba y Lola',
  'Blumarine',
  'Boadicea the Victorious',
  'Bogue Profumo',
  'Bois 1920',
  'Bois de Jasmin',
  'Bond No. 9',
  'Borouj',
  'Bottega Veneta',
  'Bottega Verde',
  'Boucheron',
  'Bourjois',
  'Boy Smells',
  'Brioni',
  'Britney Spears',
  'Brooks Brothers',
  'Bruno Acampora',
  'Bruno Banani',
  'Bruno Fazzolari',
  'Brut',
  'Bugatti',
  'Burberry',
  'Bvlgari',
  'By Kilian',
  'Byblos',
  'Byredo',
  'Cacharel',
  'Calvin Klein',
  'Carner Barcelona',
  'Carolina Herrera',
  'Caron',
  'Carrera',
  'Carthusia',
  'Cartier',
  'Carven',
  'Casamorati',
  'Caudalie',
  'Celine',
  'Celine Dion',
  'Cerruti',
  'Cesare Paciotti',
  'Chabaud Maison de Parfum',
  'Chanel',
  'Chantecaille',
  'Charles Jourdan',
  'Chloé',
  'Chopard',
  'Christian Audigier',
  'Christian Lacroix',
  'Christian Louboutin',
  'Christian Provenzano',
  'Cire Trudon',
  'Clarins',
  'Clean',
  'Clean Reserve',
  'Clinique',
  'Clive Christian',
  'Coach',
  'Collistar',
  'Comme des Garçons',
  'Commodity',
  'Comptoir Sud Pacifique',
  'Costume National',
  'Coty',
  'Courrèges',
  'Creed',
  'Cristiano Ronaldo',
  'Custo Barcelona',
  'Cyzone',
  'Czech & Speake',
  'D.S. & Durga',
  'Daniel Hechter',
  'David Beckham',
  'Davidoff',
  'Dedcool',
  'Desigual',
  'Diesel',
  'Dior',
  'Diptyque',
  'DKNY',
  'Dolce & Gabbana',
  'Donna Karan',
  'Dsquared2',
  'Dua Fragrances',
  'Dunhill',
  'Dusita',
  "Eau d'Italie",
  'Ed Hardy',
  'Eight & Bob',
  'Electimuss',
  'Elie Saab',
  'Elizabeth Arden',
  'Elizabeth Taylor',
  'Ellen Tracy',
  'Ellis Brooklyn',
  'Emanuel Ungaro',
  'Emilio Pucci',
  'Emper',
  'Emporio Armani',
  'Enrico Coveri',
  'Ensar Oud',
  'Eric Buterbaugh',
  'Eris Parfums',
  'Ermenegildo Zegna',
  'Escada',
  'Escentric Molecules',
  'Ésika',
  'Esprit',
  'Essential Parfums',
  'Estée Lauder',
  "Etat Libre d'Orange",
  'Etro',
  'Eudora',
  'Ex Idolo',
  'Ex Nihilo',
  'Fa Paris',
  'Fabergé',
  'Façonnable',
  'Farina 1709',
  'Fendi',
  'Ferrari',
  'Fila',
  'Filippo Sorcinelli',
  'Fiorucci',
  'Floraïku',
  'Floral Street',
  'Floris London',
  'Folie à Plusieurs',
  'Fragonard',
  'Fragrance Du Bois',
  'Fragrance World',
  'Francesca Bianchi',
  'Frapin',
  'Frédéric Malle',
  'French Avenue',
  'Fresh',
  'Fueguia 1833',
  'Fugazzi',
  'Gai Mattiolo',
  'Galimard',
  'Gallivant',
  'Geoffrey Beene',
  'Geza Schoen',
  'Gianfranco Ferré',
  'Giardini di Toscana',
  'Giorgio Armani',
  'Giorgio Beverly Hills',
  'Giorgio Grati',
  'Givenchy',
  'Gloria Vanderbilt',
  'Goldfield & Banks',
  'Granado',
  'Grès',
  'Gucci',
  'Guerlain',
  'Guess',
  'Gulf Orchid',
  'Gunther Gerlach',
  'Guy Laroche',
  'Gwen Stefani',
  'Halloween',
  'Halston',
  'Hamidi',
  'Hanae Mori',
  'Heeley',
  'Heidi Klum',
  'Hermès',
  'Hermetica',
  'Hilary Duff',
  'Hinode',
  'Hiram Green',
  'Histoires de Parfums',
  'Hollister',
  'Honoré des Prés',
  'Houbigant',
  'House of Sillage',
  'Hugo Boss',
  'Huitième Art Parfums',
  'Humiecki & Graef',
  'Hummer',
  'Ibraheem Al Qurashi',
  'Iceberg',
  'Il Profvmo',
  'Imaginary Authors',
  'Indult',
  'Ineke',
  'Ines de la Fressange',
  'Initio',
  'Issey Miyake',
  'Iunx',
  'Jacques Battini',
  'Jacques Bogart',
  'Jacques Zolty',
  'Jafra',
  'Jaguar',
  'Jean Desprez',
  'Jean Patou',
  'Jean Paul Gaultier',
  'Jean-Louis Scherrer',
  'Jennifer Lopez',
  'Jequiti',
  'Jessica Simpson',
  'Jil Sander',
  'Jimmy Choo',
  'Jo Malone London',
  'John Galliano',
  'John Varvatos',
  'Joop!',
  'Jovoy Paris',
  'Juicy Couture',
  'Jul et Mad',
  'Juliette Has a Gun',
  'Junaid',
  'Jusbox',
  'Justin Bieber',
  'Karl Lagerfeld',
  'Kate Moss',
  'Kate Spade',
  'Katy Perry',
  'Kayali',
  'Keiko Mecheri',
  'Kenneth Cole',
  'Kenzo',
  'Kerosene',
  'Khadlaj',
  "Kiehl's",
  'Kierin NYC',
  'Kim Kardashian',
  'Korres',
  'Krizia',
  "L'Artisan Parfumeur",
  "L'Bel",
  "L'Erbolario",
  "L'Occitane",
  'La Closerie des Parfums',
  'La Perla',
  'La Prairie',
  'Laboratorio Olfattivo',
  'Lacoste',
  'Lady Gaga',
  'Lalique',
  'Lamborghini',
  'Lancaster',
  'Lancôme',
  'Lanvin',
  'Lattafa',
  'Lattafa Pride',
  'Laura Biagiotti',
  'Laura Mercier',
  'Le Falcone',
  'Le Jardin Retrouvé',
  'Le Labo',
  'Lenthéric',
  'Les Indémodables',
  'Ligne St Barth',
  'Liquides Imaginaires',
  'Liz Claiborne',
  'Loewe',
  'Lolita Lempicka',
  'Lorenzo Pazzaglia',
  'Lorenzo Villoresi',
  'Lotto',
  'Louis Féraud',
  'Louis Vuitton',
  'Lubin',
  'Lucky Brand',
  'Lush',
  'Luzi',
  'Mad et Len',
  'Madonna',
  'Maison Alhambra',
  'Maison Anthony Marmin',
  'Maison Asrar',
  'Maison Crivelli',
  'Maison Francis Kurkdjian',
  'Maison Margiela',
  'Maison Matine',
  'Maison Micallef',
  'Maison Rebatchi',
  'Maison Tahité',
  'Maison Violet',
  'Maître Parfumeur et Gantier',
  'Majda Bekkali',
  'Mancera',
  'Mandarina Duck',
  'Marbert',
  'Marc Ecko',
  'Marc Jacobs',
  "Marc O'Polo",
  'Marc-Antoine Barrois',
  'Mariah Carey',
  'Marissa Pavone',
  'Marks & Spencer',
  'Mary Kay',
  'Mary-Kate and Ashley',
  'Maserati',
  'Masque Milano',
  'Mast',
  'Matiere Premiere',
  'Mauboussin',
  'Mäurer & Wirtz',
  'Max Factor',
  'Max Mara',
  'Mazzolari',
  'MDCI',
  'Memo Paris',
  'Mémoire Liquide',
  'Mendittorosa',
  'Meo Fusciuni',
  'Mercedes-Benz',
  'Mexx',
  'Michael Kors',
  'Mikimoto',
  'Milestone',
  'Miller Harris',
  'Mind Games',
  'Missoni',
  'Miu Miu',
  'Mizensir',
  'Molinard',
  'Molton Brown',
  'Montale',
  'Montblanc',
  'Moschino',
  'Mugler',
  'My Perfumes',
  'Mykonos',
  'Nabeel',
  'Naj Oleari',
  'Nanadebary',
  'Naomi Campbell',
  'Narciso Rodriguez',
  'Nasomatto',
  'Natura',
  'Nautica',
  'Neela Vermeire Creations',
  'Nejma',
  'Nest Fragrances',
  'Nicki Minaj',
  'Nicolai',
  'Nicole Miller',
  'Nike',
  'Nina Ricci',
  'Nishane',
  'Nobile 1942',
  'Noble Isle',
  'Nomenclature',
  'Nusuk',
  'O Boticário',
  'Ojar',
  'Old Spice',
  'Olfactive Studio',
  'Ona Saez',
  'Orientica',
  'Oriflame',
  'Original Penguin',
  'Origins',
  'Oriza L. Legrand',
  'Orlane',
  'Orlov Paris',
  'Ormonde Jayne',
  'Orto Parisi',
  'Oscar de la Renta',
  'Pacha',
  'Paco Rabanne',
  'Pantheon Roma',
  'Papillon Artisan Perfumes',
  "Parfum d'Empire",
  'Parfumerie Generale',
  'Parfumerie Moderne',
  'Parfums Berdoues',
  'Parfums de Marly',
  'Parfums de Nicolaï',
  'Paris Corner',
  'Paris Hilton',
  'Patou',
  'Paul & Joe',
  'Paul Sebastian',
  'Paul Smith',
  "Paula Cahen d'Anvers",
  'Pendora Scents',
  "Penhaligon's",
  'Pepe Jeans',
  'Perris Monte Carlo',
  'Perry Ellis',
  'Phebo',
  'Phlur',
  'Pierre Cardin',
  'Pierre Guillaume',
  'Pinrose',
  'Playboy',
  'Police',
  'Porsche Design',
  'Prada',
  'Prince Matchabelli',
  'Profumum Roma',
  'Puig',
  'Puma',
  'Pupa',
  'Puredistance',
  'Quentin Bisch',
  'Ralph Lauren',
  'Rance 1795',
  'Rasasi',
  'Rayhaan',
  'Reebok',
  'Reef Perfumes',
  'Reminiscence',
  'Revillon',
  'Revlon',
  'Ricci Ricci',
  'Rihanna',
  'Riiffs',
  'Robert Piguet',
  'Roberto Cavalli',
  'Roberto Verino',
  'Roccobarocco',
  'Rochas',
  'Roger & Gallet',
  'Rogue Perfumery',
  'Roja Dove',
  'Roja Parfums',
  'Rolls-Royce',
  'Rook Perfumes',
  'Room 1015',
  'Rosendo Mateu',
  'Rubini',
  'Rue Broca',
  's.Oliver',
  'Salvador Dalí',
  'Salvatore Ferragamo',
  'Sana Jardin',
  'Santa Maria Novella',
  'Sapil',
  'Sarah Baker',
  'Sarah Jessica Parker',
  'Sean John',
  'Selena Gomez',
  'Serge Lutens',
  'Sergio Soldano',
  'Sergio Tacchini',
  'Shakira',
  'Shiseido',
  'Shu Uemura',
  'Simone Andreoli',
  'Sisley',
  'Sixteen92',
  'Skylar',
  'Slumberhouse',
  'Snif',
  'Sofia Vergara',
  'Sol de Janeiro',
  'Sonia Rykiel',
  'Sora Dora',
  'Sospiro',
  'State of Mind',
  'Stella McCartney',
  'Stéphane Humbert Lucas',
  'Strangelove NYC',
  'Strellson',
  'Sultan Pasha Attars',
  'Sumbul',
  'Surrati',
  'Swarovski',
  'Swiss Arabian',
  'Tableau de Parfums',
  'Tauer Perfumes',
  'Taylor of Old Bond Street',
  'Taylor Swift',
  'Ted Baker',
  'Teo Cabanel',
  "Tesori d'Oriente",
  'Thameen',
  'The Body Shop',
  'The Merchant of Venice',
  'Thomas Kosmala',
  'Tiffany & Co.',
  'Tiziana Terenzi',
  'Tocca',
  'Tom Daxon',
  'Tom Ford',
  'Tom Tailor',
  'Tommy Bahama',
  'Tommy Hilfiger',
  'Tory Burch',
  'Toskovat',
  'Tous',
  'Trish McEvoy',
  'Trumper',
  'Trussardi',
  'Ulrich Lang',
  'Un Jardin en Mediterranee',
  "Unique'e Luxury",
  'Valentino',
  'Van Cleef & Arpels',
  'Vera Wang',
  'Vero Profumo',
  'Versace',
  'Vertus',
  "Victoria's Secret",
  'Victorio & Lucchino',
  'Viktor&Rolf',
  'Viktoria Minya',
  'Vilhelm Parfumerie',
  'Vivienne Westwood',
  'Volnay',
  'Weil',
  'Widian',
  'Worth',
  'Xerjoff',
  'Xinu',
  'Yanbal',
  'Yardley',
  'Yohji Yamamoto',
  'Yves Rocher',
  'Yves Saint Laurent',
  'Zadig & Voltaire',
  'Zara',
  'Zarkoperfume',
  'Zielinski & Rozen',
  'Zimaya',
  'Zoologist',
];
